# Database —> pakai variabel individual Railway
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Server —> Railway inject PORT otomatis
server.port=${PORT:8080}

# Thymeleaf
spring.thymeleaf.cache=true
spring.thymeleaf.encoding=UTF-8

spring.application.name=finlit
